# Configuration parameters for training
weights: "/content/drive/MyDrive/yolov9Training_matrice/yolov9/weights/yolov9-c.pt"
cfg: "/content/drive/MyDrive/yolov9Training_matrice/yolov9/models/detect/yolov9-c_custom.yaml"
data: "/content/drive/MyDrive/yolov9Training_matrice/yolov9/data.yaml"
hyp: "data/hyps/hyp.scratch-high.yaml"
epochs: 10
batch_size: 4
img_size: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: 300
bucket: ""
cache: "ram"
image_weights: false
device: 0
multi_scale: false
single_cls: false
optimizer: "SGD"
sync_bn: false
workers: 8
project: "runs/train"
name: "exp"
exist_ok: false
quad: false
cos_lr: false
flat_cos_lr: false
fixed_lr: false
label_smoothing: 0.0
patience: 100
freeze: [0]
save_period: -1
seed: 0
local_rank: -1
min_items: 0
close_mosaic: 0

# Logger arguments
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: "latest"

